Repository wecode-bootcamp-korea/16-2nd-starbugs-frontend, pull requests merged in 2021-02, with the labels that each got.

#4 [16기 황인태] Social login 레이아웃 및 기능 구현
  .gitignore
  public/index.html
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Styles/reset.scss
  src/config.js
  src/images/coffee_bg.jpg
  src/images/kakao_btn.png
  src/images/login_bg.jpg
  src/images/mem_check_off.png
  src/images/mem_check_on.png
Labels: Status: 리뷰 요청

#7 [16기 김병진] Navbar 오류 해결
  src/Components/Nav/Components/Menunav.js
  src/Components/Nav/Components/Menunav.scss
  src/Components/Nav/Components/Subnav.scss
Labels: Status: Accepted

#5 [16기 김병진] Footer 페이지 레이아웃 완료
  package-lock.json
  package.json
  public/Images/footerlogo.png
  src/Components/Footer/Footer.js
  src/Components/Footer/Footerdata.js
  src/Components/Footer/Footersubtitle.js
  src/Components/Footer/Footertitle.js
Labels: Status: 수정 요청, Status: 컨플릭트 해결 요청

#10 [16기 김병진] Footer mockdata 수정 완료
  src/Components/Footer/Footerdata.js
Labels: Status: 리뷰 요청

#11 [16기 황인태] Product Detail 레이아웃 및 기능 구현
  package-lock.json
  public/data/product.json
  public/data/productDetailData.json
  src/Components/Footer/Footer.js
  src/Components/Nav/Components/Menunav.js
  src/Pages/Login/Login.js
  src/Pages/ProductDetail/Components/Badge.js
  src/Pages/ProductDetail/Components/Buybtns.js
  src/Pages/ProductDetail/Components/CtrlAmount.js
  src/Pages/ProductDetail/Components/ProductNutritionsInfo.js
  src/Pages/ProductDetail/Components/Smap.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetail.scss
  src/Routes.js
  src/config.js
  src/images/productDetail/icon_arrow.png
  src/images/productDetail/icon_home.png
  src/index.js
Labels: Status: 리뷰 요청

#6 [16기 김병진] Mainpage 레이아웃 구현 완료 (2/4 리뷰반영 완료)
  package-lock.json
  package.json
  public/Images/background.jpg
  public/Images/coffeee.jpg
  public/Images/favorite.png
  public/Images/logo2.jpg
  public/Images/notice.png
  public/Images/promotion.png
  public/Images/search.png
  public/Images/stabugs1.png
  public/Images/stabugs2.png
  public/Images/stabugs3.png
  public/index.html
  src/Components/Nav/Components/Menunav.js
  src/Components/Nav/Components/Subnav.js
  src/Components/Nav/Components/Subnav.scss
  src/Components/Nav/NavData.js
  src/Pages/Main/Component/MainScroll.js
  src/Pages/Main/Main.js
  src/Pages/Main/Maindata.js
  src/Routes.js
  src/ScrollTop.js
  src/config.js
Labels: Status: 리뷰 요청

#12 [16기 황인태] 로그인 페이지 오타수정, 로그인 라우터 설정
  src/Pages/Login/Login.js
  src/config.js
Labels: Status: 리뷰 요청

#1 [16기 정선미] List 페이지 레이아웃 및 기능 구현
  package-lock.json
  package.json
  public/data/productList.json
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductList/Components/ClassificationBox/ClassificationBox.js
  src/Pages/ProductList/Components/ClassificationBox/ClassificationBoxCheckbox.js
  src/Pages/ProductList/Components/ClassificationBox/ClassificationBoxCheckbox.scss
  src/Pages/ProductList/Components/NoResult.js
  src/Pages/ProductList/Components/Nutrition/Nutrition.js
  src/Pages/ProductList/Components/NutritionMap/NutritionMap.js
  src/Pages/ProductList/Components/Product/Product.js
  src/Pages/ProductList/Components/Product/Product.scss
  src/Pages/ProductList/Components/ProductCategory/ProductCategory.js
  src/Pages/ProductList/Components/ProductCategory/ProductCategory.scss
  src/Pages/ProductList/Components/ProductMap/ProductMap.js
  src/Pages/ProductList/Components/SubCategory/SubCategory.js
  src/Pages/ProductList/Components/SubCategory/SubCategory.scss
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductList.scss
  src/Styles/theme.js
  src/config.js
  src/index.js
Labels: Status: 수정 요청

#15 [16기 김병진] Mainpage 스크롤 바 오류 수정
  src/Pages/Main/Main.js
Labels: Status: 리뷰 요청

#17 [16기 황인태] 최종 체크
  src/Pages/Login/Login.scss
  src/Pages/ProductList/ProductList.js
Labels: Status: 리뷰 요청
